# Generated by Django 6.1 on 2026-08-25 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(default='EMITIDA', max_length=30)),
                ('transaccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='transacciones.transaccion')),
            ],
        ),
    ]
