# Generated by Django 6.1 on 2026-08-25 00:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('divisas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tasa_cambio', models.DecimalField(decimal_places=6, max_digits=15)),
                ('monto_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EXITOSA', 'Exitosa'), ('FALLIDA', 'Fallida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('modalidad', models.CharField(max_length=30)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='usuarios.cliente')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='transacciones.metodopago')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='divisas.moneda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='usuarios.usuario')),
            ],
        ),
    ]
