# Generated by Django 5.2.17 on 2026-09-10 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0001_initial'),
        ('usuarios', '0002_alter_cliente_options_cliente_documento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioPagoCliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alias', models.CharField(help_text='Nombre corto para identificarlo (ej. "Cuenta Itaú", "Tigo Money").', max_length=100)),
                ('identificador', models.CharField(help_text='Nº de cuenta, alias de billetera o dato equivalente.', max_length=100)),
                ('titular', models.CharField(blank=True, default='', max_length=150)),
                ('estado', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios_pago', to='usuarios.cliente')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medios_pago_cliente', to='transacciones.metodopago')),
            ],
            options={
                'ordering': ['cliente', 'alias'],
                'constraints': [models.UniqueConstraint(fields=('cliente', 'metodo_pago', 'identificador'), name='medio_pago_cliente_unico')],
            },
        ),
    ]
