# Generated by Django 5.2.17 on 2026-09-20 02:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_mediopagocliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='comision_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=5),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='monto_comision',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='modalidad',
            field=models.CharField(default='DIGITAL', max_length=30),
        ),
    ]
