# Generated by Django 5.2.17 on 2026-10-06 22:23

import django.db.models.deletion
from django.db import migrations, models


# Tipos que se cargaban a mano (texto libre) -> tipo del catálogo nuevo.
TIPOS_ANTERIORES = {
    'CASH': 'EFECTIVO', 'EFECTIVO': 'EFECTIVO', 'FISICO': 'EFECTIVO',
    'BANCO': 'TRANSFERENCIA', 'TRANSFERENCIA': 'TRANSFERENCIA', 'CUENTA': 'TRANSFERENCIA',
    'WALLET': 'BILLETERA', 'BILLETERA': 'BILLETERA',
    'TARJETA': 'TARJETA_CREDITO', 'CREDITO': 'TARJETA_CREDITO', 'TARJETA_CREDITO': 'TARJETA_CREDITO',
}


def tipos_al_catalogo(apps, schema_editor):
    """Pasa el ``tipo`` libre de cada método de pago a uno del catálogo. Lo
    que no se reconoce (ni por el tipo ni por el nombre) queda como efectivo,
    que no necesita cuenta en el banco y por lo tanto sigue funcionando."""
    MetodoPago = apps.get_model('transacciones', 'MetodoPago')
    for metodo in MetodoPago.objects.all():
        tipo = TIPOS_ANTERIORES.get(metodo.tipo.strip().upper())
        if tipo is None:
            nombre = metodo.nombre.lower()
            if 'tarjeta' in nombre:
                tipo = 'TARJETA_CREDITO'
            elif 'billetera' in nombre:
                tipo = 'BILLETERA'
            elif 'transferencia' in nombre or 'banc' in nombre:
                tipo = 'TRANSFERENCIA'
            else:
                tipo = 'EFECTIVO'
        metodo.tipo = tipo
        metodo.save(update_fields=['tipo'])


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0001_initial'),
        ('transacciones', '0003_transaccion_comision_porcentaje_and_more'),
    ]

    operations = [
        migrations.RunPython(tipos_al_catalogo, migrations.RunPython.noop),
        migrations.AddField(
            model_name='transaccion',
            name='cantidad_destino',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='medio_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='transacciones.mediopagocliente'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='moneda_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_destino', to='divisas.moneda'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='observacion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='tasa_cambio_destino',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='tipo',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia bancaria'), ('BILLETERA', 'Billetera electrónica'), ('TARJETA_CREDITO', 'Tarjeta de crédito')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('CAMBIO', 'Cambio entre divisas')], max_length=20),
        ),
    ]
