# Generated by Django 5.2.17 on 2026-10-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0004_medios_con_banco_y_cambio_entre_divisas'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='proveedor_pago',
            field=models.CharField(blank=True, default='PASARELA_LOCAL', max_length=50),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='referencia_pago_externo',
            field=models.CharField(blank=True, help_text='ID o Token devuelto por la pasarela de pago externa', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PENDIENTE_PAGO', 'Pendiente de Pago Externo'), ('PAGADO', 'Pagado'), ('EXITOSA', 'Exitosa'), ('FALLIDA', 'Fallida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20),
        ),
    ]
