# Generated by Django 5.2.17 on 2026-10-10 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        ('usuarios', '0003_categoria_define_limite_por_operacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionCajero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='activa')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_cajero', to='caja.sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_cajero', to='usuarios.usuario')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sucursal', 'usuario'), name='asignacion_cajero_unica')],
            },
        ),
    ]
