# Generated by Django 5.2.17 on 2026-10-10 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_asignacioncajero'),
        ('divisas', '0001_initial'),
        ('usuarios', '0003_categoria_define_limite_por_operacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arqueo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('total_esperado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_contado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='DetalleArqueo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_esperada', models.PositiveIntegerField()),
                ('cantidad_contada', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StockBillete',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='billete',
            options={'ordering': ['moneda__codigo', 'denominacion']},
        ),
        migrations.RemoveField(
            model_name='billete',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='billete',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='cajero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='movimientobillete',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_billetes', to='usuarios.usuario'),
        ),
        migrations.AddConstraint(
            model_name='billete',
            constraint=models.UniqueConstraint(fields=('moneda', 'denominacion'), name='billete_moneda_denominacion_unica'),
        ),
        migrations.AddConstraint(
            model_name='caja',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTA')), fields=('cajero',), name='un_cajero_una_caja_abierta'),
        ),
        migrations.AddField(
            model_name='arqueo',
            name='caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arqueos', to='caja.caja'),
        ),
        migrations.AddField(
            model_name='arqueo',
            name='cajero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arqueos', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='arqueo',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arqueos', to='divisas.moneda'),
        ),
        migrations.AddField(
            model_name='detallearqueo',
            name='arqueo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='caja.arqueo'),
        ),
        migrations.AddField(
            model_name='detallearqueo',
            name='billete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_arqueo', to='caja.billete'),
        ),
        migrations.AddField(
            model_name='stockbillete',
            name='billete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='caja.billete'),
        ),
        migrations.AddField(
            model_name='stockbillete',
            name='caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_billetes', to='caja.caja'),
        ),
        migrations.AddConstraint(
            model_name='stockbillete',
            constraint=models.UniqueConstraint(fields=('caja', 'billete'), name='stock_billete_unico'),
        ),
    ]
