# Generated by Django 5.2.17 on 2026-10-10 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_arqueo_detallearqueo_stockbillete_and_more'),
        ('divisas', '0001_initial'),
        ('usuarios', '0005_merge_20261010_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_apertura', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField()),
                ('operaciones', models.PositiveIntegerField(default=0)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres', to='caja.caja')),
                ('cajero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cierres_de_su_caja', to='usuarios.usuario')),
                ('cerrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_realizados', to='usuarios.usuario')),
            ],
            options={
                'ordering': ['-fecha_cierre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCierre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=15)),
                ('recibido', models.DecimalField(decimal_places=2, max_digits=15)),
                ('entregado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_final', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_contado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='caja.cierrecaja')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_cierre', to='divisas.moneda')),
            ],
            options={
                'ordering': ['moneda__codigo'],
            },
        ),
    ]
