# Generated by Django 5.2.17 on 2026-10-11 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_cierre_de_caja'),
        ('divisas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteStock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('moneda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='limite_stock', to='divisas.moneda')),
            ],
            options={
                'verbose_name': 'límite de stock',
                'verbose_name_plural': 'límites de stock',
                'ordering': ['moneda__codigo'],
            },
        ),
    ]
