# Generated by Django 6.1 on 2026-08-25 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('orden', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado'), ('SUSPENDIDO', 'Suspendido'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('orden', models.IntegerField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='proyectos.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backlog', to='proyectos.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionProyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='usuarios.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='usuarios.usuario')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='proyectos.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('duracion', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado'), ('SUSPENDIDO', 'Suspendido'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='proyectos.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('prioridad', models.IntegerField(default=0)),
                ('urgencia', models.IntegerField(default=0)),
                ('horas_estimadas', models.IntegerField(default=0)),
                ('valor_tecnico', models.IntegerField(default=0)),
                ('valor_negocio', models.IntegerField(default=0)),
                ('estado_finalizacion', models.CharField(default='To-Do', max_length=30)),
                ('aprobado', models.BooleanField(default=False)),
                ('horas_trabajadas', models.IntegerField(default=0)),
                ('backlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stories', to='proyectos.backlog')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_stories', to='proyectos.estado')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_stories', to='proyectos.sprint')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_stories', to='usuarios.usuario')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_stories', to='proyectos.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('user_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='proyectos.userstory')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='proyectos.workflow'),
        ),
        migrations.CreateModel(
            name='Worklog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horas', models.IntegerField()),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('user_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to='proyectos.userstory')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worklogs', to='usuarios.usuario')),
            ],
        ),
    ]
