# Generated by Django 5.2.17 on 2026-10-06 22:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(help_text='Nº de cuenta, de tarjeta o de billetera.', max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('CUENTA', 'Cuenta bancaria'), ('BILLETERA', 'Billetera electrónica'), ('TARJETA_CREDITO', 'Tarjeta de crédito')], max_length=20)),
                ('entidad', models.CharField(help_text='Banco o emisor (ej. "Banco Itaú", "Tigo Money").', max_length=100)),
                ('titular_documento', models.CharField(max_length=50, verbose_name='documento / RUC del titular')),
                ('titular_nombre', models.CharField(max_length=150)),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='disponible')),
                ('linea_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Solo para tarjetas de crédito.', max_digits=15, verbose_name='línea de crédito')),
                ('estado', models.BooleanField(default=True, verbose_name='activa')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'cuenta bancaria',
                'verbose_name_plural': 'cuentas bancarias',
                'ordering': ['titular_nombre', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoBancario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('DEBITO', 'Débito'), ('CREDITO', 'Crédito')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_resultante', models.DecimalField(decimal_places=2, max_digits=15)),
                ('concepto', models.CharField(max_length=200)),
                ('referencia', models.CharField(blank=True, default='', max_length=50)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='banco.cuentabancaria')),
            ],
            options={
                'verbose_name': 'movimiento bancario',
                'verbose_name_plural': 'movimientos bancarios',
                'ordering': ['-fecha_hora', '-id'],
            },
        ),
    ]
