# Generated by Django 6.1 on 2026-08-25 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('simbolo', models.CharField(max_length=10)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Simulacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_operacion', models.CharField(max_length=30)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('resultado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tasa_compra', models.DecimalField(decimal_places=6, max_digits=15)),
                ('tasa_venta', models.DecimalField(decimal_places=6, max_digits=15)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('origen', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasas', to='divisas.moneda')),
            ],
        ),
    ]
