# Generated by Django 5.2.17 on 2026-09-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(help_text='Ej: USD, EUR, BRL', max_length=10)),
                ('tasa_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tasa_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
            },
        ),
    ]
