"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga de variables de entorno desde el .env de la raíz del proyecto.
# Cada variable define como default el valor actual de desarrollo, así el
# proyecto sigue funcionando aunque no exista el archivo .env (AMB - Hito 3).
env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env(
    'SECRET_KEY',
    default='django-insecure--+*--5n-!ctf29nkjph0m3ns@blg1430ctd2g!uknh%+#=36#8',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])


# Application definition

INSTALLED_APPS = [
    # Apps de Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party
    'rest_framework',
    'mozilla_django_oidc',

    # Módulos de Global Exchange
    'apps.usuarios',
    'apps.proyectos',
    'apps.caja',
    'apps.divisas',
    'apps.transacciones',
    'apps.facturacion',
    'apps.notificaciones',
    'apps.reportes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME', default='Global_Exchange'),
        'USER': env('DB_USER', default='postgres'),
        'PASSWORD': env('DB_PASSWORD', default='123456'),
        'HOST': env('DB_HOST', default='localhost'),  # o la IP del contenedor/WSL
        'PORT': env('DB_PORT', default='5432'),
    }

}

# Default primary key field type
# https://docs.djangoproject.com/en/6.1/ref/settings/#default-auto-field
# Coincide con el tipo con el que se crearon las tablas (migración 0001);
# no genera migraciones y silencia los avisos models.W042.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
# Se usa en el alta de usuario por el administrador (RF3): la contraseña
# generada se envía al correo del usuario. Por defecto (desarrollo) el backend
# de consola imprime el correo en la terminal; en producción se setea
# EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend y EMAIL_HOST_PASSWORD
# por variable de entorno (fuera del control de versiones).

EMAIL_BACKEND = env(
    'EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend'
)
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='globalexchange314@gmail.com')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env(
    'DEFAULT_FROM_EMAIL', default='GlobalExchange <globalexchange314@gmail.com>'
)

# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    # TODO: reemplazar por autenticación/permisos vía Keycloak (RF4) cuando
    # esté disponible el IAM centralizado.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}


# Autenticación OIDC con Keycloak
AUTHENTICATION_BACKENDS = (
    'apps.usuarios.backends.CustomOIDCBackend',
    'django.contrib.auth.backends.ModelBackend',
)

OIDC_RP_CLIENT_ID = env('OIDC_RP_CLIENT_ID', default='django-backend')
# El secreto real del cliente OIDC no debe quedar en el código fuente (QA -
# Hito 4): se lee de la variable de entorno OIDC_RP_CLIENT_SECRET y, si no
# está definida, se usa el secreto actual del realm de desarrollo como
# default para no romper el entorno local de nadie del equipo.
OIDC_RP_CLIENT_SECRET = env(
    'OIDC_RP_CLIENT_SECRET',
    default='tNPOCqVu0s7H09kQgrGYLhXuGCPC72bd5vYbdeZ82WEEBzsP7Zi47OJ9tsIuIvpAjLYOa4BTnVBNEw1JnKQvel',
)

# Acceso a Keycloak: dos URLs distintas porque, corriendo en Docker, Django y
# el navegador de cada usuario NO ven a Keycloak en la misma dirección.
# - KEYCLOAK_SERVER_URL: la usa el propio proceso de Django puertas adentro
#   (intercambio de tokens, JWKS, API admin). En Docker Compose es el nombre
#   del servicio ("http://keycloak:8080/"); corriendo todo en la máquina
#   local coincide con KEYCLOAK_PUBLIC_URL.
# - KEYCLOAK_PUBLIC_URL: a la que se redirige el NAVEGADOR del usuario (login,
#   logout, Account Console). Tiene que ser una URL que la máquina de cada
#   usuario pueda resolver, por eso en Docker sigue siendo "localhost:8080"
#   (el puerto publicado del contenedor), nunca el nombre del servicio.
KEYCLOAK_SERVER_URL = env('KEYCLOAK_SERVER_URL', default='http://localhost:8080/')
KEYCLOAK_PUBLIC_URL = env('KEYCLOAK_PUBLIC_URL', default='http://localhost:8080/')
KEYCLOAK_REALM = env('KEYCLOAK_REALM', default='GlobalExchange')
KEYCLOAK_ADMIN_USER = env('KEYCLOAK_ADMIN_USER', default='admin')
KEYCLOAK_ADMIN_PASSWORD = env('KEYCLOAK_ADMIN_PASSWORD', default='admin')

_KC_SERVER_BASE = KEYCLOAK_SERVER_URL.rstrip('/')
_KC_PUBLIC_BASE = KEYCLOAK_PUBLIC_URL.rstrip('/')

# Los dos que arman una URL a la que redirige el navegador van con la URL
# pública; el resto son llamadas que hace Django mismo, server-to-server.
OIDC_OP_AUTHORIZATION_ENDPOINT = f'{_KC_PUBLIC_BASE}/realms/{KEYCLOAK_REALM}/protocol/openid-connect/auth'
OIDC_OP_LOGOUT_ENDPOINT = f'{_KC_PUBLIC_BASE}/realms/{KEYCLOAK_REALM}/protocol/openid-connect/logout'
OIDC_OP_TOKEN_ENDPOINT = f'{_KC_SERVER_BASE}/realms/{KEYCLOAK_REALM}/protocol/openid-connect/token'
OIDC_OP_USER_ENDPOINT = f'{_KC_SERVER_BASE}/realms/{KEYCLOAK_REALM}/protocol/openid-connect/userinfo'
OIDC_OP_JWKS_ENDPOINT = f'{_KC_SERVER_BASE}/realms/{KEYCLOAK_REALM}/protocol/openid-connect/certs'

OIDC_RP_SIGN_ALGO = 'RS256'
LOGIN_URL = '/oidc/authenticate/'
LOGIN_REDIRECT_URL = '/'

# Cierre de sesión: además de borrar la sesión local, cerramos la sesión SSO en
# Keycloak (RP-initiated logout). ``provider_logout_url`` arma la URL con el
# id_token como hint, por eso guardamos el id_token en la sesión. Vuelve a la
# pantalla pública de cotizaciones ('/'), visible sin login, en vez de
# devolver directo al login de Keycloak. Ya cubierto por el post-logout
# redirect URI registrado en Keycloak (comodín 'http://127.0.0.1:8000/*',
# ver configure_keycloak_logout).
LOGOUT_REDIRECT_URL = '/'
OIDC_OP_LOGOUT_URL_METHOD = 'apps.usuarios.oidc.provider_logout_url'
OIDC_STORE_ID_TOKEN = True


# Endurecimiento de seguridad para producción (AMB - Hito 3).
# Solo se aplica cuando DEBUG=False; en desarrollo estos ajustes quedan
# desactivados para no entorpecer el trabajo local (HTTP sin TLS).
# Cada valor puede ajustarse por variable de entorno según el despliegue.
if not DEBUG:
    # Forzar HTTPS y marcar las cookies como seguras.
    SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=True)
    SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=True)
    CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=True)

    # HTTP Strict Transport Security (1 año).
    SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=31536000)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool(
        'SECURE_HSTS_INCLUDE_SUBDOMAINS', default=True
    )
    SECURE_HSTS_PRELOAD = env.bool('SECURE_HSTS_PRELOAD', default=True)

    # Detrás de un proxy inverso (Nginx, etc.) que termina TLS.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
