# Generated by Django 6.1 on 2026-08-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('FISICA', 'Persona física'), ('JURIDICA', 'Persona jurídica')], max_length=20)),
                ('categoria', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('limite_compra', models.DecimalField(decimal_places=2, max_digits=15)),
                ('limite_venta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('frecuencia_transacciones', models.IntegerField(default=0)),
                ('preferencia_tipo_cambio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('permisos', models.ManyToManyField(blank=True, related_name='roles', to='usuarios.permiso')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=200)),
                ('estado', models.BooleanField(default=True)),
                ('clientes', models.ManyToManyField(blank=True, related_name='usuarios', to='usuarios.cliente')),
                ('roles', models.ManyToManyField(blank=True, related_name='usuarios', to='usuarios.rol')),
            ],
        ),
    ]
