# Generated by Django 5.2.17 on 2026-08-30 13:42

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='cliente',
            name='documento',
            field=models.CharField(default='SIN-DOCUMENTO', help_text='Documento de identidad o RUC. Identificador único del cliente.', max_length=50, unique=True, verbose_name='documento / RUC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='categoria',
            field=models.CharField(choices=[('MINORISTA', 'Minorista'), ('CORPORATIVO', 'Corporativo'), ('VIP', 'VIP')], default='MINORISTA', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='limite_compra',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='limite_venta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='preferencia_tipo_cambio',
            field=models.CharField(choices=[('ESTANDAR', 'Estándar'), ('PREFERENCIAL', 'Preferencial'), ('MAYORISTA', 'Mayorista')], default='ESTANDAR', max_length=20),
        ),
    ]
