# Generated by Django 5.2.17 on 2026-10-06 22:18

from django.db import migrations, models


def corporativo_a_mayorista(apps, schema_editor):
    """La categoría "Corporativo" pasa a llamarse "Mayorista"."""
    Cliente = apps.get_model('usuarios', 'Cliente')
    Cliente.objects.filter(categoria='CORPORATIVO').update(categoria='MAYORISTA')


def mayorista_a_corporativo(apps, schema_editor):
    Cliente = apps.get_model('usuarios', 'Cliente')
    Cliente.objects.filter(categoria='MAYORISTA').update(categoria='CORPORATIVO')


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_cliente_options_cliente_documento_and_more'),
    ]

    operations = [
        migrations.RunPython(corporativo_a_mayorista, mayorista_a_corporativo),
        migrations.RemoveField(
            model_name='cliente',
            name='limite_compra',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='limite_venta',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='categoria',
            field=models.CharField(choices=[('MINORISTA', 'Minorista'), ('MAYORISTA', 'Mayorista'), ('VIP', 'VIP')], default='MINORISTA', max_length=20),
        ),
    ]
