# Generated by Django 5.2.17 on 2026-10-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0001_initial'),
        ('usuarios', '0002_alter_cliente_options_cliente_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='monedas_favoritas',
            field=models.ManyToManyField(blank=True, limit_choices_to={'activa': True}, related_name='usuarios_favoritos', to='divisas.moneda'),
        ),
    ]
