# Generated by Django 5.2.17 on 2026-10-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0001_initial'),
        ('usuarios', '0003_usuario_monedas_favoritas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='monedas_favoritas',
            field=models.ManyToManyField(blank=True, limit_choices_to={'estado': True}, related_name='usuarios_favoritos', to='divisas.moneda'),
        ),
    ]
