# Generated by Django 5.2.17 on 2026-10-10 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_categoria_define_limite_por_operacion'),
        ('usuarios', '0004_alter_usuario_monedas_favoritas'),
    ]

    operations = [
    ]
